### ISSUE TITLE
Add-on Startup Failed

### ISSUE THREAD

**Issue by CharlieDerby** [akdor1154/ankitunes#10]
Hi, I attempted to install this add-on but it's failing to start. This is the debug info I get from the fresh install:
```
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.19045

When loading AnkiTunes:
Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "C:\Users\charl\AppData\Roaming\Anki2\addons21\1456964007\__init__.py", line 1, in <module>
    from . import tune_overview
  File "C:\Users\charl\AppData\Roaming\Anki2\addons21\1456964007\tune_overview.py", line 10, in <module>
    from . import tune_reviewer
  File "C:\Users\charl\AppData\Roaming\Anki2\addons21\1456964007\tune_reviewer.py", line 26, in <module>
    Scheduler = Union[anki.scheduler.v1.Scheduler, anki.scheduler.v2.Scheduler]
AttributeError: module 'anki.scheduler' has no attribute 'v1'
```
Investigating the error I saw this section of `tune_reviewer.py` (lines 21-26)
```
if TYPE_CHECKING:
	import anki.scheduler.v1
	import anki.scheduler.v2

HTML = NewType("HTML", str)
Scheduler = Union[anki.scheduler.v1.Scheduler, anki.scheduler.v2.Scheduler]
```
I don't know much about the TYPE_CHECKING variable but I thought that maybe `anki.scheduler.v1` wasn't being imported so I tried adding the lines
```
import anki.scheduler.v1
import anki.scheduler.v2
```
just afterwards. Opening Anki after this still resulted in failure but now the debug info is this:
```
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.19045

When loading AnkiTunes:
Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "C:\Users\charl\AppData\Roaming\Anki2\addons21\1456964007\__init__.py", line 1, in <module>
    from . import tune_overview
  File "C:\Users\charl\AppData\Roaming\Anki2\addons21\1456964007\tune_overview.py", line 10, in <module>
    from . import tune_reviewer
  File "C:\Users\charl\AppData\Roaming\Anki2\addons21\1456964007\tune_reviewer.py", line 25, in <module>
    import anki.scheduler.v1
ModuleNotFoundError: No module named 'anki.scheduler.v1'
```

I'm afraid I'm out of my depth at this point so maybe you can help me out here.

Thank you :)

**Comment by stevelinberg** [comment]
Same error with latest macosx and anki 25.02.

Anki 25.02 (038d85b1)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-15.3.2-arm64-arm-64bit

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AnkiTunes ['1456964007', 2022-03-26T01:08, 'None', '']

===IDs of active AnkiWeb add-ons===
1456964007

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

When loading AnkiTunes:
Traceback (most recent call last):
  File "aqt.addons", line 250, in loadAddons
  File "/Users/slinberg/Library/Application Support/Anki2/addons21/1456964007/__init__.py", line 1, in <module>
    from . import tune_overview
  File "/Users/slinberg/Library/Application Support/Anki2/addons21/1456964007/tune_overview.py", line 10, in <module>
    from . import tune_reviewer
  File "/Users/slinberg/Library/Application Support/Anki2/addons21/1456964007/tune_reviewer.py", line 26, in <module>
    Scheduler = Union[anki.scheduler.v1.Scheduler, anki.scheduler.v2.Scheduler]
AttributeError: module 'anki.scheduler' has no attribute 'v1'
