### ISSUE TITLE
Crash when try to load a non-Tune card

### ISSUE THREAD

**Issue by akdor1154** [akdor1154/ankitunes#4]
```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.44 (b2b3275f) Python 3.9.5 Qt 5.15.2 PyQt 5.15.4
Platform: Linux
Flags: frz=False ao=True sv=2
Add-ons, last update check: 2021-06-19 18:08:36
Add-ons possibly involved: ⁨AnkiTunes⁩

Caught exception:
Traceback (most recent call last):
  File "/home/jarrad/.local/lib/python3.9/site-packages/anki/notes.py", line 141, in _fieldOrd
    return self._fmap[key][0]
KeyError: 'Tune Type'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jarrad/.local/lib/python3.9/site-packages/aqt/webview.py", line 36, in cmd
    return json.dumps(self.onCmd(str))
  File "/home/jarrad/.local/lib/python3.9/site-packages/aqt/webview.py", line 135, in _onCmd
    return self._onBridgeCmd(str)
  File "/home/jarrad/.local/lib/python3.9/site-packages/aqt/webview.py", line 580, in _onBridgeCmd
    return self.onBridgeCmd(cmd)
  File "/home/jarrad/.local/lib/python3.9/site-packages/aqt/reviewer.py", line 343, in _linkHandler
    self._answerCard(int(url[4:]))
  File "/home/jarrad/.local/lib/python3.9/site-packages/aqt/reviewer.py", line 274, in _answerCard
    self.nextCard()
  File "/home/jarrad/.local/lib/python3.9/site-packages/aqt/reviewer.py", line 124, in nextCard
    self._showQuestion()
  File "/home/jarrad/.local/lib/python3.9/site-packages/aqt/reviewer.py", line 202, in _showQuestion
    q = gui_hooks.card_will_show(q, c, "reviewQuestion")
  File "/home/jarrad/.local/lib/python3.9/site-packages/aqt/hooks_gen.py", line 778, in __call__
    text = filter(text, card, kind)
  File "/home/jarrad/.local/share/Anki2/addons21/1456964007/tune_reviewer.py", line 103, in on_card_will_show_qn
    cards = turn_card_into_set(cast(FocusCard, card), mw().col)
  File "/home/jarrad/.local/share/Anki2/addons21/1456964007/tune_reviewer.py", line 50, in turn_card_into_set
    tune_type_val = focus_note['Tune Type']
  File "/home/jarrad/.local/lib/python3.9/site-packages/anki/notes.py", line 146, in __getitem__
    return self.fields[self._fieldOrd(key)]
  File "/home/jarrad/.local/lib/python3.9/site-packages/anki/notes.py", line 143, in _fieldOrd
    raise KeyError(key) from exc
KeyError: 'Tune Type'

```

Fix: should not try to load non-Tune cards in sets.

**Comment by akdor1154** [comment]
fixed
